server:
  port: 7080

spring:
  application:
    name: gateway-service-v1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service-v1
          uri: lb://user-service-v1
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter

        - id: movie-service-v1
          uri: lb://movie-service-v1
          predicates:
            - Path=/movies/**
          filters:
            - AuthenticationFilter

        - id: identity-service-v1
          uri: lb://identity-service-v1
          predicates:
            - Path=/auth/**
  main:
    web-application-type: reactive  # This is added to ignore the conflict with spring mvc
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:7761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2